# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    branches: "master"
    paths-ignore:
      - '**/README.md'
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches: "*"
    paths-ignore:
      - '**/README.md'
  

env:
  DOTNET_NOLOGO: false
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner : [ windows-latest, ubuntu-latest, macos-latest ]
        project: [ Server ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Publish
        run: dotnet publish ${{ matrix.project }} -c Release -o release -p:PublishSingleFile=true --self-contained false '-p:DebugType=None'
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.project }}-${{ runner.os }}-${{ runner.arch }}
          path: ${{ github.workspace }}/release/*
          
  release:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          path: release/
        
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: release/*
          generateReleaseNotes: true
          skipIfReleaseExists: true
          
      - name: Create Dev Release
        uses: ncipollo/release-action@v1.12.0
#        if: github.ref == 'refs/heads/master'
        with:
          allowUpdates: true
          artifacts: release/*
          generateReleaseNotes: false
          makeLatest: true
          prerelease: true
          replacesArtifacts: true
   